### ISSUE TITLE
Notebook based versions of this course

### ISSUE THREAD

**Issue by cibinmathew** [swaroopch/byte-of-python#104]
Thanks for this wonderful bytes.

**Feature Request**

Can we create a Jupyter notebook or google colab notebook .
This will help to run the snippet within the page and the learner may not need to navigate/copy away to another editor/IDE.

**Comment by swaroopch** [comment]
Hi @cibinmathew ,

Thanks for the feature request. 

I agree with the objective of making it easy to run the Python code.

My concern is that (a) typing it out is a great way to familiarize with the details leading to comfort in _writing_ code, (b) it adds a layer of accidental complexity that may trip folks new to programming who may not understand a notebook UI.

Choosing an editor / IDE / UI can be quite involved, hence I recently added this link - https://github.com/swaroopch/byte-of-python/commit/239134197cc453397b0540fa051392af6b47f9f3

I'm happy to add a link in the book to a public notebook if the community creates one :)

**Comment by adreyer666** [comment]
Can I recommend [spyder](https://github.com/spyder-ide/spyder) as an alternative IDE?
`python -m pip install -U spyder`
