### ISSUE TITLE
PDF Document Properties "Commenting: Not Allowed" 

### ISSUE THREAD

**Issue by rjt** [swaroopch/byte-of-python#18]
![pdf-commentingnotallowed](https://cloud.githubusercontent.com/assets/360343/7205181/10fd5ffc-e4ed-11e4-9247-879e0302df69.png)
Right Click on the PDF Document, choose Document Properties, click Security Tab.

   "Commenting: Not Allowed"

i was hoping to add comments and bookmarks and hilighting to parts of the document.  

Newest (2014-12-02) or older versions of the PDF have the same issue.  Have not figured out how to generate my own yet.

**Comment by swaroopch** [comment]
Oh, that's strange. I don't recall configuring any such flags, I just use [asciidoctor and fopub](https://github.com/swaroopch/byte_of_python/blob/master/commands.bash#L21) to generate the PDF, I wonder if there are any flags there.

**Comment by rjt** [comment]
Not 100% certain but looks like commenting is only enabled if the PDF editing software has a secret Adobe only key.  Hope to be proven wrong.  Will post some links to some StackExchange site questions.

**Comment by rjt** [comment]
http://www.pdfconverter.com/resources/pdftips/howtounlockpdf
Maybe pdfconverter purchased a special license from Adobe?

I hate DRM.  This is more promising http://tex.stackexchange.com/questions/6306/how-to-annotate-pdf-files-generated-by-pdflatex

**Comment by swaroopch** [comment]
@rjt Now that I have switched to GitBook-generated PDFs, can you please check?
