### ISSUE TITLE
Display issues with the "less than or equal to (<=)" operator

### ISSUE THREAD

**Issue by notfoss** [swaroopch/byte-of-python#24]
In the operators chapter, the less than or equal to operator is not being shown properly.

On the web version, it shows up as a unicode character:

![web](https://cloud.githubusercontent.com/assets/2672831/10018667/38804f40-6156-11e5-914b-ae86e850d553.png)

and in the pdf version, it shows as a hash symbol:

![pdf](https://cloud.githubusercontent.com/assets/2672831/10018676/4f319c1c-6156-11e5-98a5-c22cf504d9c3.png)

**Comment by swaroopch** [comment]
Hmm, this is asciidoctor doing some magic.

**Comment by i-akbari** [comment]
In Page 51 and 53 this problem has occurred. .

**Comment by swaroopch** [comment]
Should be fixed now, after migrating to Markdown+GitBook.
