### ISSUE TITLE
C++ rendered as C[]+ and C+ in intro.asciidoc

### ISSUE THREAD

**Issue by jdjohnston** [swaroopch/byte-of-python#25]
Lines 65 and 66 refer to "C++" but are translated to "C[]+" and "C+", respectively, in HTML (and ePUB, ...).

**Comment by swaroopch** [comment]
Sigh, I think this is asciidoctor doing some magic, I don't have a timeline on how to fix this, but others have reported similar issues and am thinking about it, thanks for letting me know!

**Comment by swaroopch** [comment]
Should be fixed now, after migrating to Markdown+GitBook.
