### ISSUE TITLE
How to rebuild EPUB with another layout?

### ISSUE THREAD

**Issue by Sylvain303** [swaroopch/byte-of-python#39]
Reading the EPUB version on a digital reader with e-paper screen is quite difficult due to some light grayed section, which are missing contrast.

Like **CAUTION** block.

Just above: https://github.com/swaroopch/byte-of-python/blob/master/functions.md#keyword-arguments

How do I re-genrate the EPUB version?

**Comment by swaroopch** [comment]
@Sylvain303 You can use https://github.com/GitbookIO/gitbook to rebuild the book in any of the export formats.
