### ISSUE TITLE
Statement Missing in Control Flow Chapter

### ISSUE THREAD

**Issue by LenKiMo** [swaroopch/byte-of-python#56]
In [Control Flow](https://python.swaroopch.com/control_flow.html) chapter, The for Loop section, the Example's explain, there is a line as:

> Remember that the else part is optional. When included, it is always executed once after the for loop is over unless a <> statement is encountered.

It seems like the <> part is lost something.

I found in source file `control_flow.md` Line 99, this location has something:

```markdown
Remember that the `else` part is optional. When included, 
it is always executed once after the `for` loop is over unless a <<the_break_statement,break>> statement is encountered.
```

So the problem seems like Markdown doesn't include this `<the_break_statement,break>` in HTML  file.
Could you check this?

**Comment by swaroopch** [comment]
Thanks!
