### ISSUE TITLE
A few remarks on README.MD

### ISSUE THREAD

**Issue by diev** [swaroopch/byte-of-python#61]
I see a nice rendered page at https://www.gitbook.com/book/swaroopch/byte-of-python/details itself but here on https://github.com/swaroopch/byte-of-python/blob/master/README.md I see some dirty things:
* `{#who-reads-bop}`
* `{{ book.officialUrl }}`
* `{{ book.buyBookUrl }}`
* `{{ book.downloadUrl }}`
* `{{ book.sourceUrl }}`

It's not a problem here but for your attention only.

**Comment by swaroopch** [comment]
The official book is at https://python.swaroopch.com - the github repo is for people who want to look at the source code, so I think this is an okay tradeoff so that I don't have to think of writing a separate README :)
