### ISSUE TITLE
op_exp.md 

### ISSUE THREAD

**Issue by liuzhibo** [swaroopch/byte-of-python#64]
> // (divide and floor)
> 
> Divide x by y and round the answer down to#  **the nearest whole number**
> 13 // 3 gives 4
> -13 // 3 gives -5

the nearest whole number？？
```
print(9/1.81)
4.972375690607735

print(9//1.81)
4.0

```

**Comment by swaroopch** [comment]
Well, since you're dividing by a float, you're getting back a float. Can reword that text.
