### ISSUE TITLE
I started working on a new Korean translation project about a week ago, and I was wondering if you could add it in translations.md?

### ISSUE THREAD

**Issue by epsimatt** [swaroopch/byte-of-python#73]
note: the project hasn't been completed yet, only 2 pages have been fully translated.

_ current progress: https://github.com/epsimatt/byte-of-python/issues/2
_ gitbook link: https://epsimatt.gitbook.io/byte-of-python/

**Comment by swaroopch** [comment]
Done! Thank you @epsimatt

**Comment by epsimatt** [comment]
👍
