### ISSUE TITLE
Download links broken + code not being displayed

### ISSUE THREAD

**Issue by MarekPikula** [swaroopch/byte-of-python#80]
Links on https://swaroop-c-h.gitbook.io/byte-of-python/#download don't work.

**Comment by swaroopch** [comment]
@MarekPikula Will look into this soon, I think the recent upgrade of my account on gitbook from legacy to non-legacy has broken things.

**Comment by MarekPikula** [comment]
I presume that _+ code not being displayed_ regards chapters from _Control flow_ on?

**Comment by swaroopch** [comment]
So far, I've learned that [Gitbook legacy is being shut down](https://docs.gitbook.com/resources/gitbook-legacy) and that [gitbook CLI is deprecated](https://docs.gitbook.com/resources/gitbook-legacy/v2-differences) and they're moving to a cloud-only service which charges for PDF downloads, etc.

At least, for the short term, I couldn't figure out how to get the inclusion of source code working. If anybody has some advice on that, would greatly appreciate it.

**Comment by swaroopch** [comment]
It's unfortunate that I didn't realize these breaking changes when they sent an email that legacy is being shut down, and they provided a button to move to the new non-legacy system :(

**Comment by swaroopch** [comment]
Got a response from GitBook support:

> GitBook v2 doesn't support source code inclusion anymore, you would need to do it manually.

**Comment by MarekPikula** [comment]
For the time being do you have these files downloaded somewhere?

**Comment by MarekPikula** [comment]
Also I think that ReadTheDocs provides similar service. Maybe it's not so much about books, but more about documentation, but still it uses Pandoc at the backend, so it's quite predictable in terms of supported feature set.

**Comment by dturaev** [comment]
Would [Jupyterbook](https://jupyterbook.org/intro.html) be an option?

**Comment by MarekPikula** [comment]
Is it possible to export to epub/mobi from Jupyterbook? I couldn't find any information about that. `nbconvert` dooesn't seem to support it.

**Comment by swaroopch** [comment]
I have a working interim solution now - [Using GitHub Actions, we run `gitbook` to generate the html website, and push to GitHub Pages](https://github.com/swaroopch/byte-of-python/blob/master/.github/workflows/main.yml) - which is now live at http://python.swaroopch.com/ (HTTPS certificate will be generated in 24 hours, so https website should be live in 24 hours)

I'm looking into generating the EPUB & PDF and see if it can be hosted using [GitHub Releases](https://github.com/actions/upload-release-asset)

/cc @MarekPikula @dturaev

**Comment by swaroopch** [comment]
PDF & EPUB are now available at https://github.com/swaroopch/byte-of-python/releases/latest

/cc @MarekPikula @dturaev
