### ISSUE TITLE
Format code using black ?

### ISSUE THREAD

**Issue by jooola** [swaroopch/byte-of-python#94]
I though this change should be discussed a bit.

I propose to format the python code using [black](https://github.com/psf/black), in order to have consistent code across the book.
Consistency is also important in coding, so I though it should be applied in a learning book.

**Comment by swaroopch** [comment]
Do you mind reviewing the diff in https://github.com/swaroopch/byte-of-python/pull/95/files and see if it looks okay?

**Comment by swaroopch** [comment]
Decided to not go ahead with this, reasoning at https://github.com/swaroopch/byte-of-python/pull/95#issuecomment-881153751
