### ISSUE TITLE
PDF file formatting

### ISSUE THREAD

**Issue by IvansNab** [swaroopch/byte-of-python#96]
Hello. I am now reading your book as my second book for Python. The book is instructive! I am trying to copy the code from the book's PDF and have problems with formatting when I paste the code into VS Code. Copying the code from your website works correctly. Attach the file from VS Code:
[function_keyword.zip](https://github.com/swaroopch/byte-of-python/files/6176360/function_keyword.zip)

Thanks.

**Comment by swaroopch** [comment]
Hi @IvansNab, unfortunately, that is to be expected from PDF files, at least, that's been my experience. I'm not sure what can be done to improve the situation.

Please let me know if you know any changes that can be done to the configuration of https://github.com/honkit/honkit and/or https://github.com/kovidgoyal/calibre which is what we use for PDF generation. The exact steps are at https://github.com/swaroopch/byte-of-python/blob/master/.github/workflows/main.yml

**Comment by IvansNab** [comment]
I am a beginner in Python programming so I can unfortunately not help fix it. I have tried copying Python code from other PDF files and code formatting works correctly. I hope that it is possible to correct. Thanks.

**Comment by swaroopch** [comment]
Closing this since it is not actionable, and a workaround is available (use the website).
